### ISSUE TITLE
Ktor http engine is never closed

### ISSUE THREAD

**Issue by hrcerqueira** [merge-api/merge-sdk-kotlin#16]
Whenever a new instance of `dev.merge.client.shared.ApiClient` is created, we can either pass in an HTTP engine, or one is created by the Ktor `HttpClient`. So essentially, if we don't explicitly reuse an HTTP engine, one will be created per each API client instance. 

The problem is that there is no way to close this new Ktor client, so it can clean up, as a result an application can easily accumulate thousands of `Ktor-client-apache` threads, eventually crashing the application.

A quick fix here would be to provide a close method (I will provide a pr for it). 

Another optimization could be to have the SDK reuse the engine across client instances somehow.

**Comment by leewang0** [comment]
Thanks so much for the contribution, @hrcerqueira
